sudo: required
dist: trusty
before_install:
- sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-full
  texlive-lang-swedish
script:
- pdflatex -interaction=nonstopmode -halt-on-error -jobname reglemente *.tex && pdflatex -interaction=nonstopmode -halt-on-error -jobname reglemente *.tex
deploy:
  provider: releases
  api_key:
    secure: egyGvCcYldby1N1wdQxrRb9HMFwbZTMUm4JMdj06qdtOPzmqTBEsd6kioW2IzeM2/M8kdP+JX9E6oOqOUnDmVUjnPbleehtVYjeNUYtocBksjevj0dTde3JXDYy1sAR/jmRYxj/06RiseI/UQqfemKF2qRVdRaUuMk+8Hm37tZRocXTnAgbb27mmV+YXCRPmVR++mD6Dx9voBGvN4TAOvVJs4DDTHLqUBZVb1NKLER+TP+fZ9P+SQJav5CAO6xpsSaSMm1K+NOd0GUDea46+Hh/AoSVLkHHPm7E0KmZ3WxRcsdfB3uBcz5IFqkG6gTrYdwtfN+YXh73RHyyoxOT9jOtMjeBHQIWFj2p1O4JajEVEqztR37wfFX8fskId6oLxCayw3fQbjkjJryhxcRp36PjhKm+XLMReFxKKSaxB2a60IsbB3zQ3Q7E+7jK3VhCJYepHYvbnp23BebcTy7EXTjxrXt2lkOTh6q06vi+ORQb4JbMI+Om0d8zMFJ1xuMKNcHDNBOHFhtPzgiyJ+jB/kUlGx73nFSx2T49FxGQBUNQfXqv9vdtVf6L4mOUoPuD+2ufIH859p+daEraNjMhMwValMjLCewDfCQn7FIJN4iUIpjaam0VhV6AHYoXyPRFs5yzZ5qDpfl3xZsoYcTD6X3CKDELoRDKDw0/QGQnipPQ=
  file: reglemente.pdf
  skip_cleanup: true
  on:
    tags: yes
    repo: Dsek-LTH/reglemente