# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Compile PDFs
run-name: "Compile PDFs"
on:
  pull_request:
    branches:
      - main
  workflow_call: {}

jobs:
  compile-pdfs:
    runs-on: ubuntu-latest
    container:
      image: texlive/texlive:latest
      env:
        TEXINPUTS: ".:..:"
    steps:
      - name: Check out document sources
        uses: actions/checkout@v4
      - name: Create build directory
        run: mkdir build
      - name: Compile statutes
        run: latexmk -outdir=../build -cd stadgar/stadgar.tex
      - name: Compile regulations
        run: latexmk -outdir=../build -cd reglemente/reglemente.tex
      - name: Compile policies
        run: |
          for filename in policyer/*.tex; do
              latexmk -outdir=../build -cd $filename
          done
      - name: Compile guidelines
        run: |
          for filename in riktlinjer/*.tex; do
              latexmk -outdir=../build -cd $filename
          done
      - name: Upload PDFs
        uses: actions/upload-artifact@v4
        with:
          name: pdfs
          path: build/*.pdf
